### get all cards
GET http://localhost:8080/api/v1/cards

### get my cards
GET http://localhost:8080/api/v1/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzUxNzQwOX0.C19C4-DiJnioTYX_I4cmvJsxfealEO423Zw2wy0FwKU

### get card by id
GET http://localhost:8080/api/v1/cards/6582bba21f5c56aeb4f4ced0

### new card
POST http://localhost:8080/api/v1/cards/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzUyMTIxM30.wsE4XI6WxB3T9Hz9wXpWoaaGDSPOO0aP9btAD0gxvmo
Content-Type: application/json

{
    "title": "new card check likes",
    "subtitle": "new card ",
    "description": "new card description",
    "phone": "050-1234567",
    "email": "e@gamil.com",
    "web": "www.google.com",
    "address": {
        "city": "new city",
        "country": "new country",
        "street": "new street",
        "houseNumber": 21
        }
    
}

### update card by id
PUT http://localhost:8080/api/v1/cards/65899d754044466cdf6d9c85
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzUxNzQwOX0.C19C4-DiJnioTYX_I4cmvJsxfealEO423Zw2wy0FwKU
Content-Type: application/json

{
    "title": "new card-new!!",
    "subtitle": "new card ",
    "description": "new card description",
    "phone": "050-2345678",
    "email": "e@gamil.com",
    "web": "www.google.com",
    "address": {
        "city": "new city",
        "country": "new country",
        "street": "new street",
        "houseNumber": 21
        }
    }

### like a card
PATCH http://localhost:8080/api/v1/cards/6582b9628cb2349e6f43cbe5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzUxNzQwOX0.C19C4-DiJnioTYX_I4cmvJsxfealEO423Zw2wy0FwKU


### delete card by id
DELETE http://localhost:8080/api/v1/cards/6589abe09c638c387a429169
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzUxNzQwOX0.C19C4-DiJnioTYX_I4cmvJsxfealEO423Zw2wy0FwKU