### get all cards
GET http://localhost:8080/api/v1/cards

### get my cards
GET http://localhost:8080/api/v1/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzA2NjIxNH0.zIuISnfLET21ZtR3USM6TL8MgNXXtmA4a6BiWRD3smA

### get card by id
GET http://localhost:8080/api/v1/cards/6582b9628cb2349e6f43cbea

### new card
POST http://localhost:8080/api/v1/cards/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzA2NjIxNH0.zIuISnfLET21ZtR3USM6TL8MgNXXtmA4a6BiWRD3smA
Content-Type: application/json

{
    "title": "new card check likes",
    "subtitle": "new card ",
    "description": "new card description",
    "phone": "050-1234567",
    "email": "e@gamil.com",
    "web": "www.google.com",
    "address": {
        "city": "new city",
        "country": "new country",
        "street": "new street",
        "houseNumber": 21
        }
    
}

### update card by id
PUT http://localhost:8080/api/v1/cards/657f256df42b7241576aaff6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJ1aXNAYnVpcy5jb20iLCJpYXQiOjE3MDI5MDQ3MTl9.cBH7NxlJJLE2-wKASuGawakPsWVMb_hf7Ah7TkZ2W-U
Content-Type: application/json

{
    "title": "new card-new!!",
    "subtitle": "new card ",
    "description": "new card description",
    "phone": "050-2345678",
    "email": "e@gamil.com",
    "web": "www.google.com",
    "address": {
        "city": "new city",
        "country": "new country",
        "street": "new street",
        "houseNumber": 21
        }
    }

### like a card
PATCH http://localhost:8080/api/v1/cards/6582b9628cb2349e6f43cbe5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzA2NjIxNH0.zIuISnfLET21ZtR3USM6TL8MgNXXtmA4a6BiWRD3smA


### delete card by id
DELETE http://localhost:8080/api/v1/cards/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzA2NjIxNH0.zIuISnfLET21ZtR3USM6TL8MgNXXtmA4a6BiWRD3smA